In [3]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

df = pd.read_excel('C:/Users/aozde/OneDrive/Documents/Columbia/Week-24/Online_retail.xlsx')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [4]:
df['Description']= df['Description'].str.strip()
df.dropna(axis =0, subset =['InvoiceNo'], inplace =True)
df['InvoiceNo'] = df['InvoiceNo'].astype('str')
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [5]:
basket= (df[df['Country']=='France'].groupby(['InvoiceNo', 'Description'])['Quantity']
        .sum().unstack().reset_index().fillna(0)
        .set_index('InvoiceNo'))
basket

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536852,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536974,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537065,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537463,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C579532,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C579562,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C580161,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C580263,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C581316,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

In [7]:
basket_sets =  basket.applymap(encode_units)

basket_sets.drop('POSTAGE', inplace=True, axis=1)
basket_sets

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C579532,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C579562,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C580161,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C580263,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C581316,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
frequent_itemsets = apriori(basket_sets, min_support=0.07,use_colnames=True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(PLASTERS IN TIN CIRCUS PARADE),(PLASTERS IN TIN SPACEBOY),0.143167,0.117137,0.075922,0.530303,4.527217,0.059152,1.879645
1,(PLASTERS IN TIN SPACEBOY),(PLASTERS IN TIN CIRCUS PARADE),0.117137,0.143167,0.075922,0.648148,4.527217,0.059152,2.435209
2,(PLASTERS IN TIN WOODLAND ANIMALS),(PLASTERS IN TIN CIRCUS PARADE),0.145336,0.143167,0.086768,0.597015,4.170059,0.065961,2.126215
3,(PLASTERS IN TIN CIRCUS PARADE),(PLASTERS IN TIN WOODLAND ANIMALS),0.143167,0.145336,0.086768,0.606061,4.170059,0.065961,2.169531
4,(PLASTERS IN TIN WOODLAND ANIMALS),(PLASTERS IN TIN SPACEBOY),0.145336,0.117137,0.088937,0.611940,5.224157,0.071913,2.275071

In [10]:
rules[(rules['lift']>=6)&(rules['confidence'] >= 0.8)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
10,(SET/6 RED SPOTTY PAPER PLATES),(SET/6 RED SPOTTY PAPER CUPS),0.108460,0.117137,0.104121,0.960000,8.195556,0.091417,22.071584
11,(SET/6 RED SPOTTY PAPER CUPS),(SET/6 RED SPOTTY PAPER PLATES),0.117137,0.108460,0.104121,0.888889,8.195556,0.091417,8.023861
12,"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",(SET/6 RED SPOTTY PAPER CUPS),0.086768,0.117137,0.084599,0.975000,8.323611,0.074435,35.314534
13,"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",(SET/6 RED SPOTTY PAPER PLATES),0.086768,0.108460,0.084599,0.975000,8.989500,0.075188,35.661605
14,"(SET/6 RED SPOTTY PAPER PLATES, SET/6 RED SPOT...",(SET/20 RED RETROSPOT PAPER NAPKINS),0.104121,0.112798,0.084599,0.812500,7.203125,0.072854,4.731743

In [ ]:
######################################################################################################

In [4]:
#Q-1
df_france = df[df['Country'] == 'France']
df_france.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France
30,536370,21883,STARS GIFT TAPE,24,2010-12-01 08:45:00,0.65,12583.0,France

In [5]:
df_france.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8557 entries, 26 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    8557 non-null   object
 1   StockCode    8557 non-null   object
 2   Description  8557 non-null   object
 3   Quantity     8557 non-null   int64
 4   InvoiceDate  8557 non-null   datetime64[ns]
 5   UnitPrice    8557 non-null   float64
 6   CustomerID   8491 non-null   float64
 7   Country      8557 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 601.7+ KB

* Question 2:


* Group the entries of df_france by InvoiceNo and Description into a series called basket. Each entry of basket should be the sum of how many times a certain product appears over all the transactions.

In [ ]:
pd.Series
n_by_state = df.groupby("state")["last_name"].count()
df.squeeze()

data = {'Products': ['Computer', 'Printer', 'Tablet', 'Chair', 'Desk']}
df = pd.DataFrame(data, columns = ['Products'])

my_series = df.squeeze()

print(my_series)
print (type(my_series))

In [11]:
basket=df_france.groupby('InvoiceNo')['Description'].sum()
print (type(basket))

<class 'pandas.core.series.Series'>

In [10]:
### GRADED

### YOUR SOLUTION HERE
basket = df_france.groupby(['InvoiceNo', 'Description']).sum().squeeze()
basket
print (type(basket))
 
 

### YOUR CODE HERE
###

<class 'pandas.core.frame.DataFrame'>

In [12]:
basket=df_france.groupby('InvoiceNo')['Description'].sum()
print (type(basket))

<class 'pandas.core.series.Series'>

* Question 3:

* Unstack the series basket to create a dataframe df_basket. Do so by using the function unstack().

* Next, reset the index of your dataframe, fill the NaN values with zeroes, and set the index column to InvoiceNo.

*HINT: The functions reset_index(), fillna() and set_index() will be useful

In [8]:
### GRADED

### YOUR SOLUTION HERE
df_basket = basket.unstack().reset_index().fillna(0).set_index('InvoiceNo')
 
df_basket.head()

                                  Quantity                     \
Description  50'S CHRISTMAS GIFT BAG LARGE  DOLLY GIRL BEAKER
InvoiceNo
536370                                 NaN                NaN
536852                                 NaN                NaN
536974                                 NaN                NaN
537065                                 NaN                NaN
537463                                 NaN                NaN

                                                                   \
Description  I LOVE LONDON MINI BACKPACK  NINE DRAWER OFFICE TIDY
InvoiceNo
536370                               NaN                      NaN
536852                               NaN                      NaN
536974                               NaN                      NaN
537065                               NaN                      NaN
537463                               NaN                      NaN

                                                                      \
Description  SET 2 TEA TOWELS I LOVE LONDON   SPACEBOY BABY GIFT SET
InvoiceNo
536370                                  24.0                     NaN
536852                                   NaN                     NaN
536974                                   NaN                     NaN
537065                                   NaN                     NaN
537463                                   NaN                     NaN

                                                       \
Description  TRELLIS COAT RACK 10 COLOUR SPACEBOY PEN
InvoiceNo
536370                     NaN                    NaN
536852                     NaN                    NaN
536974                     NaN                    NaN
537065                     NaN                    NaN
537463                     NaN                    NaN

                                                                  ...  \
Description 12 COLOURED PARTY BALLOONS 12 EGG HOUSE PAINTED WOOD  ...
InvoiceNo                                                         ...
536370                             NaN                       NaN  ...
536852                             NaN                       NaN  ...
536974                             NaN                       NaN  ...
537065                             NaN                       NaN  ...
537463                             NaN                       NaN  ...

                             CustomerID                                 \
Description WRAP VINTAGE PETALS  DESIGN YELLOW COAT RACK PARIS FASHION
InvoiceNo
536370                              0.0                            0.0
536852                              0.0                            0.0
536974                              0.0                            0.0
537065                              0.0                            0.0
537463                              0.0                            0.0

                                                                     \
Description YELLOW GIANT GARDEN THERMOMETER YELLOW SHARK HELICOPTER
InvoiceNo
536370                                  0.0                     0.0
536852                                  0.0                     0.0
536974                                  0.0                     0.0
537065                                  0.0                     0.0
537463                                  0.0                     0.0

                                                                  \
Description ZINC  STAR T-LIGHT HOLDER  ZINC FOLKART SLEIGH BELLS
InvoiceNo
536370                             0.0                       0.0
536852                             0.0                       0.0
536974                             0.0                       0.0
537065                             0.0                       0.0
537463                             0.0                       0.0

                                                                    \
Description ZINC HERB GARDEN CONTAINER ZINC METAL HEART DECORATION
InvoiceNo
536370                             0.0                         0.0
536852                             0.0                         0.0
536974                             0.0                         0.0
537065                             0.0                         0.0
537463                             0.0                         0.0


Description ZINC T-LIGHT HOLDER STAR LARGE ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo
536370                                 0.0                             0.0
536852                                 0.0                             0.0
536974                                 0.0                             0.0
537065                                 0.0                             0.0
537463                                 0.0                             0.0

[5 rows x 4695 columns]

* Question 4:

* Define a function, encode_units that takes one float, x. Your function should return 0 if x is less than or equal to zero or 1 if x is greater than or equal to one.

* Use the function applymap() to apply this function to your dataframe df_basket. Assign the new dataframe to basket_sets.

* Finally, remove the POSTAGE column.

In [11]:
def encode_unit(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

In [13]:
### GRADED

### YOUR SOLUTION HERE
basket_sets =  df_basket.applymap(encode_unit)

basket_sets.drop('POSTAGE', inplace=True, axis=1)



        
    

###
### YOUR CODE HERE
###

KeyError: 'POSTAGE'

* Question 5:

* Use the function apriori from the mlxtend library on basket_sets to create a dataframe frequent_itemsets with the support for each item. Set the arguments of apriori to min_support = 0.07 and use_colnames = True

In [14]:
### GRADED

### YOUR SOLUTION HERE

frequent_itemsets = apriori(basket_sets, min_support=0.07,use_colnames=True)

###
### YOUR CODE HERE
###

ValueError: The allowed values for a DataFrame are True, False, 0, 1. Found value nan

* The final step is to generate the rules with their corresponding support, confidence, and lift. We can do so using the function association_rules from mlxtend.
* Question 6:
* Use the function association_rules from mlxtend to create the decided dataframe from frequent_itemsets. Name this dataframe rules. Set the arguments metric= "lift".

In [15]:
### GRADED

### YOUR SOLUTION HERE

rules = association_rules(frequent_itemsets, metric="lift",
min_threshold=1)
rules.head()

###
### YOUR CODE HERE
###

NameError: name 'frequent_itemsets' is not defined